#!/bin/bash

# PATH ~/dotfiles
DOTFILES=$(ls -a ~/dotfiles | awk '/^\.[a-z]+/')

for DOTFILE in ${DOTFILES[@]}
do
	LINK_PATH=~/${DOTFILE}
	USE_FILE=~/dotfiles/${DOTFILE}

	if [ ${DOTFILE} == ".gitignore_global" ]; then
		ln -sfv ${USE_FILE} ${LINK_PATH}
		git config --global core.excludesfile ~/.gitignore_global
	fi

	if [[ ${DOTFILE} =~ ^(\.git) ]]; then
		continue
	fi

	if [ -e ${LINK_PATH} ]; then
		rm -rf ${LINK_PATH}
	fi
	ln -sfv ${USE_FILE} ${LINK_PATH}
done


