#!/bin/sh

TIG_VERSION="tig-2.5.3"
curl -OL https://github.com/jonas/tig/releases/download/$TIG_VERSION/$TIG_VERSION.tar.gz
tar -xzf $TIG_VERSION.tar.gz
cd $TIG_VERSION

# 日本語対応させてビルド
# url : https://qiita.com/tdrk/items/06b21bedff3244e21aae
# for cc aclocal
yum install gcc automake
./autogen.sh
./configure --without-ncurses
make prefix=/usr/local
make install prefix=/usr/local

cd ..
rm -rf $TIG_VERSION*

# if you want to uninstall
# make uninstall prefix=/usr/local
